Remove-Printer -Name "EE-DeansOffice-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "EE-ICD-EPSON" -ErrorAction SilentlyContinue
Remove-Printer -Name "EE-MainOffice-HP-ColorA" -ErrorAction SilentlyContinue
Remove-Printer -Name "EE-RM201-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "EE-TeacherOffice-Konica-BnW" -ErrorAction SilentlyContinue
Remove-Printer -Name "EE-TeacherOffice-Konica-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "EE-PrincipalOffice-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "EM-TeachersOffice-Konica" -ErrorAction SilentlyContinue
Remove-Printer -Name "EM-TeachersOffice-Konica-BnW" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-MainOffice-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-MainOffice-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-MainOffice-HP-Joanna" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-Principal-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-RM402-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-RM403-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-RM405-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-RM406-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-RM407-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-RM408-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-RM411-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-RM412-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-RM414-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-RM415-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-RM417-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-Rm419-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-Rm421A-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-RM425-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-TeachersOffice-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-TRC-Konica" -ErrorAction SilentlyContinue
Remove-Printer -Name "WM-TRC-Konica-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "74W-RM116-Konica-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "74W-RM303-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "74W-RM315-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "74W-RM316-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "74W-Rm404-KONICA" -ErrorAction SilentlyContinue
Remove-Printer -Name "74W-RM413-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "74W-RM503-HP-Color1" -ErrorAction SilentlyContinue
Remove-Printer -Name "74W-Rm516A-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "74W-RM517A-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "74W-RM517A-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "74W-RM517B-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "74W-Rm517B-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "74W-RMB16-Konica-BnW" -ErrorAction SilentlyContinue
Remove-Printer -Name "74W-RMB16-Konica-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "74W-RmB7-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "EE-PrekOffice-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "EM-DeansOffice-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "EM-RM436B-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "HS-RM111-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "HS-Rm315-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "HS-Rm318-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "HS-RM407-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "HS-Rm507-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "HS-RM508-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "HS-RM509-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "HS-Rm510-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "HS-RM511A-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "HS-Rm511-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "HS-TeachersOffice-Konica" -ErrorAction SilentlyContinue
Remove-Printer -Name "HS-TeachersOffice-Konica1" -ErrorAction SilentlyContinue
Remove-Printer -Name "HS-WelcomeCenter-HP" -ErrorAction SilentlyContinue
Remove-Printer -Name "HS-WelcomeCenter-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "PEI-1stFl-Toshiba5506" -ErrorAction SilentlyContinue
Remove-Printer -Name "EE-DeansOffice-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "EE-ICD-HP-Color" -ErrorAction SilentlyContinue
Remove-Printer -Name "EE-MainOffice-HP-Color" -ErrorAction SilentlyContinue